# Generated by Django 4.1.1 on 2022-09-15 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zayavki', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationtest',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Комментарий'),
        ),
    ]
