# Generated by Django 4.1.1 on 2022-09-16 00:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('zayavki', '0002_applicationtest_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationtest',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
